### ISSUE TITLE
hello how can i get blackout matches data?

### ISSUE THREAD

**Issue by cimpdev** [Lierrmm/Node-CallOfDuty#1]
how can i get blackout matches data?

crm/cod/v2/title/bo4/platform/battle/gamer/jutes%2311766/matches/days/7

this link get matches data but only mp data i wanna blackout matches data

**Comment by Lierrmm** [comment]
Hi,

The Link Would be /crm/cod/v2/title/bo4/platform/battle/gamer/jutes%2311766/profile/type/blackout

it's under the mp object. Can't see anything for blackout games though.

Will take a deeper look tonight.

**Comment by cimpdev** [comment]
@Lierrmm i want not profile data. i wanna matches data. but you are code only profile data

**Comment by Lierrmm** [comment]
because there is no match data for blackout.

**Comment by Lierrmm** [comment]
think it may be weeks, so 0 would be first week etc - it will be used for getting only a certain amount of data.
