### ISSUE TITLE
Cannot get successful response using endpoints that require unoId

### ISSUE THREAD

**Issue by smac60** [Lierrmm/Node-CallOfDuty#118]
I am able to retrieve data for endpoints that use gamertag/platform.  For example this works with no issues.  All the data is coming back correctly:

let data = await api.ModernWarfare.combatHistory(gamertag, api.platforms.XBOX);

However, whenever I try to use an endpoint that requires a unoId.  Like this:
 **let data = await ModernWarfare3.fullData(unoId)**

I am getting the following error:

**{
  status: 'error',
  data: {
    type: 'java.lang.Exception',
    message: 'Error validating auth token'
  }
}**

I have even tried to get the unoId from the combatHistory endpoint and use that but I am still getting the same error.

Any ideas what I might be doing wrong here?

**Comment by Lierrmm** [comment]
MW2/WZ2 and mw3 endpoints no longer work.
