### ISSUE TITLE
How to Transfer my activition ID to linked blizzard ID

### ISSUE THREAD

**Issue by neil-yagao** [Lierrmm/Node-CallOfDuty#12]
Hi there, 
First of all, a great appreciation for what you have done for such wrap. It provides much convenient for a developer to get the data needed. 
Meanwhile, I am facing the issue that I need to get user War Zone match information and I could only get user Activision Id. Is it possible for me to get the linked account Id (which could be directly consumed by your API) from the Activision ID?
To make my question clear, my Activision Id is "Sabrina#6133335" and this is the only thing I could acquire from my customer automatically. However, if I want to use your API, I had to feed it with "SABRINA#11295" which could only be found after I login into my call of duty profile under the linked account.

**Comment by Lierrmm** [comment]
Can I ask what level your profile is?

This just makes the process of finding a way easier for me.
Thanks

**Comment by neil-yagao** [comment]
Thanks for you quick reply. I do not quite understand what do you mean by level?

**Comment by Lierrmm** [comment]
your in game level, what rank?

**Comment by neil-yagao** [comment]
Level 51

**Comment by Lierrmm** [comment]
Update:

Haven't found a way to find battlenet id through activision ID but you can search via activision ID for stats so I will implement that as a platform later today.

I wont close this until then.

**Comment by neil-yagao** [comment]
Much appreciate! Looking forward to it

**Comment by Lierrmm** [comment]
I have published a new version.
Just use `npm i call-of-duty-api@latest` to get the changes.

Here is an example:
```javascript
const api = require('./index.js')({ platform: 'uno' });
const user = "Sabrina#6133335";
api.MWwz(user).then(console.log).catch(console.log); 
```

Please let me know how it goes and then I can close the issue.

**Comment by neil-yagao** [comment]
I just try the new API. It works like a charm. Huge thanks.
