### ISSUE TITLE
Cannot read property 'psn' of undefined

### ISSUE THREAD

**Issue by M0in4** [Lierrmm/Node-CallOfDuty#13]
I got:
Cannot read property 'psn' of undefined

When I try:
const API = require('call-of-duty-api');
apiGame = API.platforms.psn;
(Same for other platforms)

**Comment by Lierrmm** [comment]
as this now uses module exports, you need to make sure you are declaring this when requiring the api.

Example:
```js
const api = require('call-of-duty-api')();
apiGame = api.platforms.psn;
console.log(apiGame)```
```
an easier way would be 
```js
const api = require('call-of-duty-api')({ platform: 'psn' });
```
this way you don't need to pass the game in every function call you make.
not passing in a platform like this, would default to PSN.
```js
const api = require('call-of-duty-api')();
```

Hope this helps.

##### I will close this issue, just open a new one if you are struggling
