### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by Nik0gda** [Lierrmm/Node-CallOfDuty#17]
![image](https://user-images.githubusercontent.com/45215396/79195294-adf3ef00-7e36-11ea-8c31-96eecfb2d0e1.png)

**Comment by Lierrmm** [comment]
This is a rate limit set by Call of Duty, you need to handle how many requests you are making better.

I will be adding rate-limiting in the future as well, which should hopefully stop these.

**Comment by Nik0gda** [comment]
I did just one request in 5 hours, and this happened, i think this issue isn't happening with me. Because some discord guilds bots that were providing Warzone Stats also failed

**Comment by Lierrmm** [comment]
I will Have a look into this. 

I will also reopen the issue.

Thanks for reporting.

**Comment by Nik0gda** [comment]
The issue is solved in 1.1.2 version
