### ISSUE TITLE
"Not permitted: not authenticated"

### ISSUE THREAD

**Issue by niklas-palm** [Lierrmm/Node-CallOfDuty#18]
As of yesterday, for all requests, the endpoint simply returns 

```json
{
   "status": "error",
   "data" : {
      "type": "com.activision.mt.common.stdtools.exceptions.NoStackTraceException"
      "message": "Not permitted: not authenticated"
   }
}
```

Any thoughts on how I can authenticate?

**Comment by Lierrmm** [comment]
What are you using to make the request? 

What username, what platform?

**Comment by niklas-palm** [comment]
The MWwz endpoint, but all related to modern warfare responds with "not logged in".
peks 24, psn.

```javascript
const API = require('call-of-duty-api')();
  
API.MWwz('peks24', API.platforms.psn).then((output) => {
    console.log(output);
}).catch((err) => {
    console.log(err);
});
```

--> 

```json
{
   "status": "error",
   "data" : {
      "type": "com.activision.mt.common.stdtools.exceptions.NoStackTraceException"
      "message": "Not permitted: not authenticated"
   }
}
```

**Comment by Lierrmm** [comment]
Call of Duty have started to rate limit. To combat this I have pushed an update ( 1.1.2 ) which is a major change.

You will need to login to a call of duty account to perform API lookups.
You can take a look at the ReadMe file which will show you how to get it all set up correctly.

Hope that helps 😄

**Comment by niklas-palm** [comment]
Awesome, thanks!
