### ISSUE TITLE
Empty response after updating to 1.0.26

### ISSUE THREAD

**Issue by Narghor** [Lierrmm/Node-CallOfDuty#19]
Hello,

I'm using your API like this : 

`    
API = require('call-of-duty-api')({ platform: "uno" });
API.MWwz('chowh1#5932193').then(data => {
		console.log(data);
})` 

I get an empty response since this morning : 

[ br: {}, br_dmz: {}, br_all: {} ] 

When i tried to use the API without the new update it has been throwing an error "mode undefined".

Now it's just an empty response :/

**Comment by Lierrmm** [comment]
Call of Duty have started to rate limit. To combat this I have pushed an update ( 1.1.2 ) which is a major change.

You will need to login to a call of duty account to perform API lookups.
You can take a look at the ReadMe file which will show you how to get it all set up correctly.

Hope that helps 😄

**Comment by Narghor** [comment]
Hello,

I created a dummy Activision account and it works just fine :)

Thank you for this quick update !
