### ISSUE TITLE
include damage for MWwz

### ISSUE THREAD

**Issue by boushib** [Lierrmm/Node-CallOfDuty#22]
right now, `damage` field is not included in the API response for warzone (`MWwz`)

**Comment by Lierrmm** [comment]
The endpoint returns two values in regards to damage, damageDone and DamageTaken.

You can find these in all of the br objects from the MWwz call.

**Comment by boushib** [comment]
![2020-04-24_12-31-58](https://user-images.githubusercontent.com/11537492/80212821-bb278f80-8627-11ea-9948-7369d36d1774.png)

**Comment by Lierrmm** [comment]
you are not using the correct endpoint. You should be using MWcombatwz not MWwz

**Comment by boushib** [comment]
`MWcombatwz` return a ton of useless data (like `63177` line of code in the json response )
we, in our case we don't need that much data, 
that will slow up our requests

![2020-04-25_2-29-10](https://user-images.githubusercontent.com/11537492/80269146-9c171500-869c-11ea-8044-867e8168f5fa.png)

**Comment by Lierrmm** [comment]
Then there is no way to get damage without it. All this wrapper does is returns exactly what CoD use themselves.
