### ISSUE TITLE
Rumble mode?

### ISSUE THREAD

**Issue by MMA15** [Lierrmm/Node-CallOfDuty#30]
Just wondering, is it possible to get rumble data using the `MWwz` endpoint? Also `MWcombatwz` does this give the 20 most recent matches or is it more than that?

**Comment by Lierrmm** [comment]
MWcombatwz has a second function that allows you to pass in a start and end timestamp in epoch, which will return all results within those times.

MWfullcombatwzdate is the function to use if you are passing in dates.

Rumble data should be included in the warzone stats but at the moment it doesn't seem to be included, unfortunately.
