### ISSUE TITLE
Gulag stats?

### ISSUE THREAD

**Issue by derocknc** [Lierrmm/Node-CallOfDuty#33]
tracker.gg seems to be getting gulag stats, at least for single games from the COD API.  Could this be a potential added feature?

**Comment by J-Swift** [comment]
The gulag stats are in the game stats already (`gulagKills` and `gulagDeaths`) but I've noticed that you can have more than 1 `gulagDeath` in a game and I'm not sure why that is.

**Comment by derocknc** [comment]
Gotcha, I could be missing it but 1) is that only available for pulling stats from one match 2) I'm not seeing where that endpoint is set up in this code, if it is.

**Comment by J-Swift** [comment]
I am pulling it from `MWcombatwz`. In that response its under `playerStats.gulagKills` and `playerStats.gulagDeaths`

**Comment by derocknc** [comment]
Thanks @J-Swift !
