### ISSUE TITLE
Last x Days Stats?

### ISSUE THREAD

**Issue by Sattishh** [Lierrmm/Node-CallOfDuty#37]
I was wondering if you have considering adding a Last x Days Stats, meaning the stats in the last x number of days.. Or in a more simple way, like a Last 7 Days Stats?

Thanks, great API btw!

**Comment by Lierrmm** [comment]
You can use MWweeklystats endpoint. There isn't a way to specify how many days at the moment. just grabs the last 7 ( Sunday to Sunday)
