### ISSUE TITLE
error when trying to get bo4 stats

### ISSUE THREAD

**Issue by lemeshovich** [Lierrmm/Node-CallOfDuty#4]
im getting that when trying to get bo4 stats(
yesterday everything works fine
`{
    "status": "error",
    "data": {
        "type": "com.activision.mt.common.stdtools.exceptions.NoStackTraceException",
        "message": "Not permitted"
    }
}`

**Comment by Lierrmm** [comment]
Pushing a fix, something to do with their endpoint expecting cookies.

**Comment by Lierrmm** [comment]
Fixed in version 1.0.17.
