### ISSUE TITLE
Player Data - [feature]

### ISSUE THREAD

**Issue by iHakeem** [Lierrmm/Node-CallOfDuty#43]
Can you guys add an command to get Player data in MW like the opened characters and skins #

**Comment by Lierrmm** [comment]
Unfortunately, this isn't possible with the data available through the API.

**Comment by iHakeem** [comment]
well, after some researches, there is an API for loadout :)

**Comment by Lierrmm** [comment]
If you can get me the endpoints for loadouts, I can add them to the wrapper, however, as far as I'm aware, the loadout endpoints are bo4 only.
