### ISSUE TITLE
uno

### ISSUE THREAD

**Issue by elreco** [Lierrmm/Node-CallOfDuty#44]
uno is not wroking :/

**Comment by luisramirez-m** [comment]
You could put more information with your problem. However I think it’s the common problem, you should use `acti` for the activision tag. `uno` is for numerical ids.

For example:

```javascript
const API = require('call-of-duty-api')({ platform: "acti" });
```

and after:

```javascript
try {
    await API.login(<username>, <password>);
 } catch(Error) {
     //Handle Exception
 }
```

```javascript
try {
   let data = await API.MWwz(<gamertag>, <platform>?);
} catch(Error) {
    //Handle Exception
}
```

More information: https://lierrmm.github.io/capi-docs/#/?id=usage
Discord: https://discord.com/invite/NuUpvzC

**Comment by Lierrmm** [comment]
> You could explain your problem. However I think it’s the common problem, you should use `acti` for the activision tag. `uno` is for numerical ids.
> 
> For example:
> 
> ```js
> const API = require('call-of-duty-api')({ platform: "acti" });
> ```
> 
> and after:
> 
> ```js
> try {
>     await API.login(<username>, <password>);
>  } catch(Error) {
>      //Handle Exception
>  }
> ```
> 
> ```js
> try {
>    let data = await API.MWwz(<gamertag>, <platform>?);
> } catch(Error) {
>     //Handle Exception
> }
> ```
> 
> More information: https://lierrmm.github.io/capi-docs/#/?id=usage
> Discord: https://discord.com/invite/NuUpvzC

Thanks @luisramirez-m.

Will keep this issue open until a reply from author or after 2 days.

**Comment by Lierrmm** [comment]
Closing after no reply.
