### ISSUE TITLE
Cant login "No device id header present"

### ISSUE THREAD

**Issue by LeanLarroza** [Lierrmm/Node-CallOfDuty#47]
Today, the api i made can't login with API.login('leanlarroza@*************', '*********').
I made a test and add + data.message after incorrect password message and this go out:
{"message":"TanoLarry: 401 - Unauthorized. Incorrect username or password. No device id header present."}

**Comment by MikeShiner** [comment]
I too can no longer log in. I just simply get..

```
Logging in..
401 - Unauthorized. Incorrect username or password.
(node:1) UnhandledPromiseRejectionWarning: 401 - Unauthorized. Incorrect username or password.
```

Using the 'battle' client

**Comment by J-Swift** [comment]
Same, but I can still use old tokens to make authenticated requests

**Comment by MikeShiner** [comment]
> Same, but I can still use old tokens to make authenticated requests

I can log in manually to my machine to generate token.
Which headers are you overriding?

**Comment by Lierrmm** [comment]
Could you jump into the discord so I can investigate further? https://discord.gg/NuUpvzC

I am able to sign device ID's but not get through to login.

**Comment by J-Swift** [comment]
@MikeShiner here is an example curl request I use all the time, only replacing the url. I copied from chrome a while back I think:

```
curl -v --cookie "XSRF-TOKEN={token}; new_SiteId=cod; comid=cod; check=true; mbox={mbox}; ACT_SSO_LOCALE={sso-locale}; ACT_SSO_COOKIE={sso-cookie}; ACT_SSO_COOKIE_EXPIRY={sso-expiry}; ACT_SSO_REMEMBER_ME={sso-remember-me}; ACT_SSO_EVENT={sso-event}; pgacct={pgacct}; CRM_BLOB={crm-blob}; agegate=; country=US; umbrellaId={umbrella-id}; at_flavor=; API_CSRF_TOKEN={csrf-token}" {url}
```

**Comment by Lierrmm** [comment]
ATVI have reverted the changes and the old login method is working as intended.

I expect them to change it back soon, so I will keep this issue open for the time being.

**Comment by Lierrmm** [comment]
Closing until ATVI update the login methods to no longer work. 

Feel free to open as and when.
