### ISSUE TITLE
Mapping guns to in game names?

### ISSUE THREAD

**Issue by kevin-wynn** [Lierrmm/Node-CallOfDuty#49]
Right now whenever you make requests for CW using the api call `CWmp`, in the `payload.lifetime.itemData` the response is grouped by weapon type and then the weapons result in something like:

```
ar_standard_t9,
ar_slowhandling_t9,
ar_slowfire_t9
...
```

Is there a way, either another API request to the call of duty servers to get the in game mapping of these weapons? Like the XM4, Ak47, etc?

**Comment by Lierrmm** [comment]
Currently, there is no way to retrieve the weapon name from the codename.

**Comment by kevin-wynn** [comment]
@Lierrmm Thanks! I will work on doing my own mapping and see if I can piece them together 👍
