### ISSUE TITLE
[403] All Stats endpoints

### ISSUE THREAD

**Issue by divanvb** [Lierrmm/Node-CallOfDuty#5]
Hi

I'm experiencing this issue at the moment 

> "Error: Request failed with status code 403"

I believe the cookie has expired that you've implemented.

```typescript
let iwStatistics = codAPI.IWStats(playerId, 'psn');
let bo3Statistics = codAPI.BO3Stats(playerId, 'psn');
let wwiiStatistics = codAPI.WWIIStats(playerId, 'psn');
let bo4Statistics = codAPI.BO4Stats(playerId, 'psn');

await Promise.all([
	iwStatistics,
	bo3Statistics,
	wwiiStatistics,
	bo4Statistics,
]);
```

**Comment by Lierrmm** [comment]
Can I ask what request you are making?

**Comment by divanvb** [comment]
These are the following requests I make:

```typescript 
let iwStatistics = await codAPI.IWStats(playerId, 'psn');
let bo3Statistics = await codAPI.BO3Stats(playerId, 'psn');
let wwiiStatistics = await codAPI.WWIIStats(playerId, 'psn');
let bo4Statistics = await codAPI.BO4Stats(playerId, 'psn');
```

**Comment by Lierrmm** [comment]
What username are you using?

Here is my test case: 

```javascript
const codAPI = require('call-of-duty-api');

const playerId = "Lierrmm";

async function run() {
    let iwStatistics = codAPI.IWStats(playerId, 'psn');
    let bo3Statistics = codAPI.BO3Stats(playerId, 'psn');
    let wwiiStatistics = codAPI.WWIIStats(playerId, 'psn');
    let bo4Statistics = codAPI.BO4Stats(playerId, 'psn');

    await Promise.all([
        iwStatistics,
        bo3Statistics,
        wwiiStatistics,
        bo4Statistics,
    ]).then((out) => {
        console.log(out);
    });
};

run();
```

and i this is the output i get.

```json
[
  {
    "status": "success",
    "data": {
      "title": "iw",
      "platform": "psn",
      "username": "Lierrmm",
      "mp": {
        "lifetime": {
          "all": {
            "kills": 12373,
            "wins": 761,
            "kdRatio": 1.0938909026611263,
            "losses": 238,
            "winRatio": 0.7617617617617618,
            "timePlayed": 398020,
            "lastUpdated": 1508872282000,
            "score": 2037368,
            "headshots": 872,
            "matchesPlayed": 1048,
            "suicides": 256,
            "xp": 83565,
            "scorePerMinute": 307.1254710818552,
            "deaths": 11311
          },
        },
      },
    },
  }
]
```

**Comment by divanvb** [comment]
Hmm that's strange because from my side I get the 403 error. Will investigate a bit more and see. 
I'm using `ScumpOfOptic08` for testing

**Comment by Lierrmm** [comment]
Weird. They should be no limitations..

I have just tested on your username and got back the actual stats. 

I will keep this issue open and keep an eye on it.

**Comment by divanvb** [comment]
Ah okay, but what I actually mean is, is there a limit on how many times a second you can call the API? 1 call per second, 1 call per 2 seconds etc? I'm going to test more now with regards to the issue I was receiving.

**Comment by Lierrmm** [comment]
No, I have never noticed a timeout when debugging.

**Comment by divanvb** [comment]
Have you tried running a lot of consecutive requests to the API and see if you get any errors then? Like say loop through 500 id's and make the requests to the API as quick as possible?

**Comment by Lierrmm** [comment]
It looks like there is now a limit of calls, looks like its around 30s to 1 minute.

**Comment by Lierrmm** [comment]
Looks like the endpoints have changed. Will be working on it today.

**Comment by divanvb** [comment]
> It looks like there is now a limit of calls, looks like its around 30s to 1 minute.

Do mean 1 requests per 30 seconds to 1 minute?

**Comment by Lierrmm** [comment]
yes, I ran a test for a full day and it looks like waiting 40 seconds between each call works perfectly.

**Comment by divanvb** [comment]
Okay cool, I'm going to test it now with a 40 seconds delay between requests. Any idea of how I would efficiently be able to query +-700 id's? Some have PSN id's, some don't.

**Comment by Lierrmm** [comment]
no idea, you may have to just tinker with the code a bit.
