### ISSUE TITLE
Recent changes in activision

### ISSUE THREAD

**Issue by 1TekPro** [Lierrmm/Node-CallOfDuty#53]
Activision changed player data to private and when I switch my profile to public/all, I get:
Not permitted: not authenticated

**Comment by Lierrmm** [comment]
What platform are you searching with?

**Comment by 1TekPro** [comment]
I have tried all of them. I suspect either the endpoint calls have changed or there is a different token requirement.

**Comment by baskeyx** [comment]
I get the same issue Tek, it looks like you can currently only pull details for the account you've authorised the initial request with.

**Comment by halshing** [comment]
Try searching your profile on CoD Tracker https://cod.tracker.gg/ -- if it's not visible there, then most likely your settings haven't updated in Activision's systems yet. My profile still say it's private even though I updated it a few hours ago. It'll probably take a day or so.

**Comment by Lierrmm** [comment]
From my understanding, you need to switch the profile to none, refresh the cod website and then back to all.

Will keep this issue open for further investigation.

**Comment by conr** [comment]
From what I can tell I can only fetch the stats of other players on my friends list and my own.

**Comment by halshing** [comment]
yep. seems like they've locked down player stats to 'not public' by default now. you can change it back to 'public', but as far as public player data for applications, it'll be much more limited now 😢

**Comment by Lierrmm** [comment]
Closing due to ATVI removing functionality to search by Activision ID.

API will be updated to reflect that.
