### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Vito2089** [Lierrmm/Node-CallOfDuty#55]
Hi everybody, 
I don't know where to get the gamertag. 
After call getLoggedInUserInfo method, the username with platform infos found inside getLoggedInUserInfo response not work with MWBattleData method that returns "404 - Not found. Incorrect username or platform? Misconfigured privacy settings?". 

Where to get the proper gametag??? 
Thanks

**Comment by Lierrmm** [comment]
getLoggedInUserInfo will return information about the user you have already logged in as. I would assume this is your account, so you would already know the gamertag and platform?

**Comment by Vito2089** [comment]
Yes it's my account, but if I use the username and the provider inside the identities list object in getLoggedInUserInfo response as gamertag it returns "404 - Not found. Incorrect username or platform? Misconfigured privacy settings?"

**Comment by Lierrmm** [comment]
Are you specifying the platform? that account listed will be your Activision account.
