### ISSUE TITLE
Fetching data without being locked in 

### ISSUE THREAD

**Issue by NZimmermann1999** [Lierrmm/Node-CallOfDuty#57]
Hi, how do I fetch my data without being locked in ? My Code looks as following : 
`const api = require('call-of-duty-api')();
const user = "Jalapa#2527";

test = () => {
    let username = user;
    let platform = api.platforms.battle;

    api.MWwz(username, platform).then(data => {
        console.log(data);
        return JSON.stringify({
            "error": "nil",
            "response": data
        });
    }).catch (err => {
        console.log(err);
        return JSON.stringify({
            "error": err,
            "response": "nil"
        });
    });
};
console.log(test());`

Why do I need to be logged in, or does my Error `Not Logged In` has a different meaning ?

**Comment by Lierrmm** [comment]
You need to be logged in because the method to grab the information from other users requires to be so.

It's a restriction from ATVI, not the wrapper.

You can login via `API.login(email, password)`
