### ISSUE TITLE
Create game room or invite friends to one

### ISSUE THREAD

**Issue by mcferdev** [Lierrmm/Node-CallOfDuty#58]
Does anybody knows how to create a game room using a api? Or invite users? 
I tried to find it in The github but haven't found.

**Comment by Lierrmm** [comment]
not sure what you mean by this?

Are you referring to invite players to your game? If so, it doesn't exist.

**Comment by mcferdev** [comment]
> not sure what you mean by this?
> 
> Are you referring to invite players to your game? If so, it doesn't exist.

Yes, it is. It´s what I mean

**Comment by Lierrmm** [comment]
Nothing like that exists in the API. Closing thread.
