### ISSUE TITLE
Login with 2fa enabled

### ISSUE THREAD

**Issue by JoostSlijkoort** [Lierrmm/Node-CallOfDuty#59]
**Is your feature request related to a problem? Please describe.**
I cannot login when 2fa is enabled. Is there a way to get this working? Login works with 2fa disabled, but this is not preferable offcourse.

**Describe the solution you'd like**
I would like to be able to login while 2fa is enabled

**Describe alternatives you've considered**
Disabling 2fa.

**Comment by Lierrmm** [comment]
There is no way around the 2FA restrictions without disabling it at this moment in time.

Best alternative is to use a throwaway account to login to the API.

**Comment by JoostSlijkoort** [comment]
I didn't think of a throwaway, that is a good solution for now. Even better, because i don't have to have my users authenticate everytime / store their credentials..
