### ISSUE TITLE
Cold War API ?

### ISSUE THREAD

**Issue by poppabear8883** [Lierrmm/Node-CallOfDuty#60]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Add support for Cold War!

**Comment by poppabear8883** [comment]
Apparently the API is there ? But not documented ?

**Comment by wesleyduff** [comment]
I am using the cold war api. Confirmed that it's not documented but easy
enough to use by searching for the exact same phrase but add CW and not MW

**Comment by Lierrmm** [comment]
Yeh, sorry about that. Documentation is outdated, but Cold War endpoints are the same as MW but prefixed with `CW` instead.

I will update the documentation at some point in the future.
