### ISSUE TITLE
Response data properties are not consistent between games (MW & CW)

### ISSUE THREAD

**Issue by poppabear8883** [Lierrmm/Node-CallOfDuty#61]
Properties are not consistent across games.

Example:

**CW** has `wlratio` vs **MW** has `wlRatio`

This creates more logic for the developers to write to handle the diff.

**Comment by wesleyduff** [comment]
Yea, I had to write code around that to manage.

Best to run the data that comes from the api through a builder / mapper.
Lowercase everything then use it in your code

This is also good to filter down the data so you are not storing huge data
objects and waste storage on items you are not using

**Comment by Lierrmm** [comment]
At this moment in time, this wrapper is only acting as a middle man, it doesn't modify any data, apart from the br only functions.

I can at some point add it as an additional module init param.
