### ISSUE TITLE
Match Details Endpoints

### ISSUE THREAD

**Issue by brmcghee** [Lierrmm/Node-CallOfDuty#62]
**Feature Request:** match details from a specific match ie: warzone lobby (multiplayer lobbies, cold war zombie lobbies if possible)

I would like to hopefully have a solution that provides details on teams, who was in each team, and their stats for that match. see link1 where you can view match history and load the scoreboard from the specific match.

**Describe alternatives you've considered**
please see link2 for reference.

**Additional context**
```
link1: https://my.callofduty.com/player/match-history (Requires Account Login)

  If you view network details via your browser it calles the following: 
https://my.callofduty.com/api/papi-client/stats/cod/v1/title/mw/platform/battle/gamer/<BATTLETAG>/profile/type/wz

link2: https://documenter.getpostman.com/view/5519582/SzzgAefq#05aa7341-d67b-4b1b-af6d-e4392baaf3cd
```

**Comment by Lierrmm** [comment]
These routes already exist in the API.

MWFullMatchInfowz - Warzone Matches
MWFullMatchInfomp - Multiplayer Matches
CWFullMatchInfo - Cold War Multiplayer Matches

Zombies lobbies arent tracked by the API so there is no way to retrieve them.
