### ISSUE TITLE
Always returns 401 - Unauthorized. Incorrect username or password. Even though my username and password is right!

### ISSUE THREAD

**Issue by GovSensei** [Lierrmm/Node-CallOfDuty#63]
is this a bug or am i just dumb?

**Comment by Lierrmm** [comment]
make sure you do not have 2fa enabled. Login is working as intended using the same method as the live website.

**Comment by bogdanaks** [comment]
Hello
Faced the same problem
Two-factor authentication is disabled

**Comment by FireCoder420** [comment]
> make sure you do not have 2fa enabled. Login is working as intended using the same method as the live website.

Do you mean https://www.activision.com ?

**Comment by Lierrmm** [comment]
> > make sure you do not have 2fa enabled. Login is working as intended using the same method as the live website.
> 
> Do you mean https://www.activision.com ?

no, the login is for my.callofduty.com. This can be different to normal Activision login.
