### ISSUE TITLE
Not permitted: not allowed

### ISSUE THREAD

**Issue by guyng** [Lierrmm/Node-CallOfDuty#65]
I'm getting this error: Not permitted: not allowed
It just started recently, anyone has the same issues?
@Lierrmm

**Comment by Lierrmm** [comment]
"Not permitted: not allowed" means you do not have permission to view the data. i.e. Your not authenticated properly or the user you are looking up has their stats set to private.

**Comment by guyng** [comment]
> "Not permitted: not allowed" means you do not have permission to view the data. i.e. Your not authenticated properly or the user you are looking up has their stats set to private.

Hm, it happens just with activision users i don't think its authentication issue because i do get the atkn, rtkn and use it in my cookie but also the users i'm trying it on the match data is being tracked fine by cod.tracker.gg  maybe activision made some changes? 
I know for a fact that the guy in the screenshot below has his stats on public but still i get the same error. can you try
to get stats for him and see if it works?
@Lierrmm 
![Screenshot_11](https://user-images.githubusercontent.com/14955499/121006029-1b7c8080-c799-11eb-98ff-866edd1b2e30.png)

**Comment by Lierrmm** [comment]
Yes, You will get this error when looking up Activision IDs. It is a change ATVI made several months ago related to other sites charging for certain information.

AFAIK, CODTracker has a deal with ATVI to retrieve this information, which is why you are able to see it on their website.

**Comment by SwiftCODA** [comment]
Hi @Lierrmm. I was about to post the same issue but then I saw this one. I'm trying to create a wrapper in Swift which is based off of your Node.js wrapper. My first step is to organize the requests with Postman. I'm getting the same error message when requesting a PlayStation user. Please feel free to point out anything I'm doing wrong in these requests.

1) registerDevice (POST)
<img width="618" alt="Screen Shot 2021-06-07 at 10 57 20 AM" src="https://user-images.githubusercontent.com/17557339/121066868-3cd07300-c77f-11eb-9503-cefe21c18554.png">

Response:
```json
{
    "status": "success",
    "exceptionMessageList": [],
    "errors": {},
    "exceptionMessageCode": null,
    "data": {
        "authHeader": "731831176a265d232f40b0a6d6f8b1b9"
    }
}
```

2) login (POST)
<img width="843" alt="Screen Shot 2021-06-07 at 10 59 05 AM" src="https://user-images.githubusercontent.com/17557339/121067112-86b95900-c77f-11eb-9814-4ca464879320.png">
<img width="606" alt="Screen Shot 2021-06-07 at 10 59 29 AM" src="https://user-images.githubusercontent.com/17557339/121067122-89b44980-c77f-11eb-95f0-9e90e3f4db3d.png">
<img width="607" alt="Screen Shot 2021-06-07 at 10 59 51 AM" src="https://user-images.githubusercontent.com/17557339/121067140-8d47d080-c77f-11eb-99d6-8b0f4afa9b66.png">

Response:
```json
{
    "rtkn": "myRtkn",
    "ACT_SSO_COOKIE": "myActSsoCookie",
    "ACT_SSO_COOKIE_EXPIRY": 1638640874103,
    "gameAccountLinked": true,
    "success": true,
    "ACT_AUTH_TOKEN": null,
    "s_ACT_SSO_COOKIE": "mySActSsoCookie",
    "atkn": "myAtkn"
}
```

3) getMWMultiplayer (GET)
<img width="839" alt="Screen Shot 2021-06-07 at 11 02 43 AM" src="https://user-images.githubusercontent.com/17557339/121067510-00514700-c780-11eb-8ba0-7a7b695e9f3b.png">
<img width="601" alt="Screen Shot 2021-06-07 at 11 03 04 AM" src="https://user-images.githubusercontent.com/17557339/121067532-06472800-c780-11eb-9cc4-1abb71c06228.png">
Main Cookie:
new_SiteId=cod; ACT_SSO_LOCALE=en_US;country=US;XSRF-TOKEN=68e8b62e-1d9d-4ce1-b93f-cbe5ff31a041;API_CSRF_TOKEN=68e8b62e-1d9d-4ce1-b93f-cbe5ff31a041;rtkn=myRtkn;ACT_SSO_COOKIE=myActSsoCookie;atkn=myAtkn;

Response:
```json
{
    "status": "error",
    "data": {
        "type": "com.activision.mt.common.stdtools.exceptions.NoStackTraceException",
        "message": "Not permitted: not allowed"
    }
}
```

**Comment by Lierrmm** [comment]
> Hi @Lierrmm. I was about to post the same issue but then I saw this one. I'm trying to create a wrapper in Swift which is based off of your Node.js wrapper. My first step is to organize the requests with Postman. I'm getting the same error message when requesting a PlayStation user. Please feel free to point out anything I'm doing wrong in these requests.
> 
> 1. registerDevice (POST)
> 
> <img alt="Screen Shot 2021-06-07 at 10 57 20 AM" width="618" src="https://user-images.githubusercontent.com/17557339/121066868-3cd07300-c77f-11eb-9503-cefe21c18554.png">
> 
> Response:
> 
> ```json
> {
>     "status": "success",
>     "exceptionMessageList": [],
>     "errors": {},
>     "exceptionMessageCode": null,
>     "data": {
>         "authHeader": "731831176a265d232f40b0a6d6f8b1b9"
>     }
> }
> ```
> 
> 1. login (POST)
> 
> <img alt="Screen Shot 2021-06-07 at 10 59 05 AM" width="843" src="https://user-images.githubusercontent.com/17557339/121067112-86b95900-c77f-11eb-9814-4ca464879320.png">
> 
> <img alt="Screen Shot 2021-06-07 at 10 59 29 AM" width="606" src="https://user-images.githubusercontent.com/17557339/121067122-89b44980-c77f-11eb-95f0-9e90e3f4db3d.png">
> 
> <img alt="Screen Shot 2021-06-07 at 10 59 51 AM" width="607" src="https://user-images.githubusercontent.com/17557339/121067140-8d47d080-c77f-11eb-99d6-8b0f4afa9b66.png">
> 
> Response:
> 
> ```json
> {
>     "rtkn": "myRtkn",
>     "ACT_SSO_COOKIE": "myActSsoCookie",
>     "ACT_SSO_COOKIE_EXPIRY": 1638640874103,
>     "gameAccountLinked": true,
>     "success": true,
>     "ACT_AUTH_TOKEN": null,
>     "s_ACT_SSO_COOKIE": "mySActSsoCookie",
>     "atkn": "myAtkn"
> }
> ```
> 
> 1. getMWMultiplayer (GET)
> 
> <img alt="Screen Shot 2021-06-07 at 11 02 43 AM" width="839" src="https://user-images.githubusercontent.com/17557339/121067510-00514700-c780-11eb-8ba0-7a7b695e9f3b.png">
> 
> <img alt="Screen Shot 2021-06-07 at 11 03 04 AM" width="601" src="https://user-images.githubusercontent.com/17557339/121067532-06472800-c780-11eb-9cc4-1abb71c06228.png">
> 
> Main Cookie: new_SiteId=cod; ACT_SSO_LOCALE=en_US;country=US;XSRF-TOKEN=68e8b62e-1d9d-4ce1-b93f-cbe5ff31a041;API_CSRF_TOKEN=68e8b62e-1d9d-4ce1-b93f-cbe5ff31a041;rtkn=myRtkn;ACT_SSO_COOKIE=myActSsoCookie;atkn=myAtkn;
> Response:
> 
> ```json
> {
>     "status": "error",
>     "data": {
>         "type": "com.activision.mt.common.stdtools.exceptions.NoStackTraceException",
>         "message": "Not permitted: not allowed"
>     }
> }
> ```

Feel free to add me on discord: Liam#0947 we can go through it step by step.

**Comment by SwiftCODA** [comment]
@Lierrmm Just added you `SwiftCODA#2497`.

**Comment by Emad-salah** [comment]
Was this issue ever solved? I see that it ended suddenly with you adding the other guy and I don't see a solution here.

**Comment by SwiftCODA** [comment]
@Emad-salah I ended up not using this API, or any COD API for that matter. I got locked out of my Discord and honestly I don't remember if we ever solved the issue or not. Sorry man.

**Comment by Lierrmm** [comment]
> Was this issue ever solved? I see that it ended suddenly with you adding the other guy and I don't see a solution here.

@Emad-salah what platform are you using when querying? ACTI and UNO will no longer work due to restrictions from the COD API itself.

**Comment by Emad-salah** [comment]
@Lierrmm sorry for the late reply didn't realize you responded. I was aware Acti and UNO won't work but the issue is showing up for me when I try to link some PSN/BNET accounts but not all of them

**Comment by Lierrmm** [comment]
I know some users have been complaining about this and it seems to be something on the COD API side. If you join the discord server, I can look into it more for you.

**Comment by Emad-salah** [comment]
great, I will join and let you know! Thank you!
