### ISSUE TITLE
404 - Not found. Incorrect username or platform? Misconfigured privacy settings?

### ISSUE THREAD

**Issue by darklight147** [Lierrmm/Node-CallOfDuty#66]
Earlier this month, my code was working

I do a fuzzySearch then grab the information of a single user for example

- user object below
```json
{
    "platform": "uno",
    "username": "Frenzla#8701238",
    "accountId": "6750249910373225069",
    "avatar": null
}
```

then pass the username & platform to the `API.MWwz(user.username, user.platform)` then it would fetch the information of the given user, now i run the same code and it gives me the Error

`404 - Not found. Incorrect username or platform? Misconfigured privacy settings?`

Am sure you would say maybe the username changed, but am sure it didn't

**Comment by Lierrmm** [comment]
You cannot look up uno tags as of January 2021. This has been blocked by Activision. You will need to lookup by the actual platform "psn", "battle", "steam", "xbl".

**Comment by darklight147** [comment]
Why does cod.tracker.gg work just fine with Activision id

**Comment by Lierrmm** [comment]
Because they have a partnership with Activision for this sort of thing.
