### ISSUE TITLE
Recaptcha error on login

### ISSUE THREAD

**Issue by smithvictor** [Lierrmm/Node-CallOfDuty#67]
When trying to perform login the following payload is received
`{
  gameAccountLinked: false,
  success: false,
  error: 'recaptcha',
  token: 'Recaptcha failed.'
}`

Package error message
`401 - Unauthorized. Incorrect username or password.`

Credentials have been verified and are correct. 2FA is not enabled on the account neither on Activision or CallOfDuty web page

**Comment by Lierrmm** [comment]
Known issue - Activision have changed the authentication method. 

Can track progress on the discord: https://discord.gg/NuUpvzC
