### ISSUE TITLE
MWAnalysis not working

### ISSUE THREAD

**Issue by SevenGuru** [Lierrmm/Node-CallOfDuty#7]
I get the following when trying to run the MWAnalysis:

`{ type:
   'com.activision.mt.common.stdtools.exceptions.NoStackTraceException',
  message: 'Not permitted: not allowed' }`

I'm going to assume we don't have access to that correct?

**Comment by Lierrmm** [comment]
Hi,

What gamertag and platform are you using when making this request.

Their API is Caps Sensitive - so doing for example lierrmm#2364 would return an error but Lierrmm#2364 would not.

**Comment by ChisdealHD** [comment]
this happen't to PSN and Xbox side API, COd have changed they mw API some reasons. because even i tried username from cod.tracker.gg example: ARWannabes as PSN name and returns that same error.

**Comment by phbrazil** [comment]
Hello guys, I'm facing the same issue passing the PSN gamer tag. Any tips? Thanks from Brazil.
