### ISSUE TITLE
401 - Unauthorized. Incorrect username or password.

### ISSUE THREAD

**Issue by Z3r0CooLE** [Lierrmm/Node-CallOfDuty#70]
When attempting to use the login API call, I get hit with a 401 exception. I have verified the email and password are correct and allow me to login to the Activision website, but I also noticed I have 2FA enabled on my Activision account. Does 2FA break the API login call and is there currently a workaround?

Thank you for any time and help provided toward this issue.

**Comment by Z3r0CooLE** [comment]
duplicate of #68

**Comment by Lierrmm** [comment]
Please see latest NPM version for 2 methods to combat this issue.
