### ISSUE TITLE
Login failing

### ISSUE THREAD

**Issue by yehezkel** [Lierrmm/Node-CallOfDuty#71]
Hello:

i know is difficult to find the workaround to make the login to work, currently on version 2.1.1 i am getting:
We Could not get a valid reason for a failure. Status: TimeoutError: Navigation timeout of 30000 ms exceeded
finished
but now sure if its because the user i am using or maybe because the recaptcha can't be bypassed by the pupetter module. 
thanks.

**Comment by Lierrmm** [comment]
30000ms is puppeteers default timeout - It sounds like either the ReCaptcha isn't succeeding OR puppeteer is not handling the redirection properly. Can you provide OS information and runtime information?

**Comment by Lierrmm** [comment]
There is an issue with some unix systems having to run puppeteer in --no-sandbox mode. You can, 1) make the change yourself to the puppeteer arguments, or I will add it on the next release build

**Comment by Lierrmm** [comment]
Change is live in version 2.1.2.
