### ISSUE TITLE
Add call to retrieve lookup values

### ISSUE THREAD

**Issue by recursivecodes** [Lierrmm/Node-CallOfDuty#73]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would be helpful to add a method to retrieve the valid lookup table for translating map names and game types.

**Describe alternatives you've considered**
Manually creating a class containing these values is an option, but they can change over time rendering that method brittle.

**Additional context**

See the output from:

https://my.callofduty.com/content/atvi/callofduty/mycod/web/en/data/json/iq-content-xweb.js

This contains a wealth of lookup values to make it easier to translate map names and game types, etc.

I've accomplished this locally by adding 2 methods, but I realize this may not be the "best" solution for your module. Still, here's how I solved it. Feel free to use the code, or adapt as necessary.

Add a method to send a raw request - the response format is different then what's utilized in `sendRequest`, thus the changes..

```
sendRawRequest(url) {
    return new Promise(((resolve, reject) => {
        loggedIn || reject("Not Logged In."), apiAxios.get(url).then((response => {
            1 === debug && (console.log("[DEBUG]", `Build URI: ${url}`), console.log("[DEBUG]", `Response Size: ${JSON.stringify(response.data).length} bytes.`)), void 0 !== response.status && 200 === response.status ? resolve(response.data) : reject(this.apiErrorHandling({
                response: response
            }))
        })).catch((error => {
            reject(this.apiErrorHandling(error))
        }))
    }))
}
```

Next, add a `getLookupValues` method to the API:

```
module.getLookupValues = function() {
    return new Promise(((resolve, reject) => {
        let urlInput = "https://my.callofduty.com/content/atvi/callofduty/mycod/web/en/data/json/iq-content-xweb.js";
        _helpers.sendRawRequest(urlInput).then((data => resolve(data))).catch((e => reject(e)))
    }))
```

The response is a giant object which uses a specific naming convention - developers can figure out their value by following the convention.

Ex:

```
{
  "maps:mw-mp_hackney_yard:1": "Hackney Yard (Night)",
  "maps:mw-mp_aniyah:1": "Aniyah Palace",
  "maps:mw-mp_euphrates:1": "Euphrates Bridge",
  ...
}
```

A few "helper" functions, for example:

```
games = [
    'mw', 'cw'
];

lookupGameMode(game, mode) {
    if( this.games.indexOf(game) == -1 ) {
        throw new Error(`Invalid game: ${game}. Must be one of: ${this.games}.`)
    }
    const key = `game-modes:${game}-${mode}:1`;
    return this.dict[key] ?? mode;
}
```

So, `lookupGameMode("cw", "conf_hc")` would return `Hardcore Kill Confirmed`.

Let me know if you have any questions.

**Comment by recursivecodes** [comment]
Bump.

**Comment by Lierrmm** [comment]
Happy to implement something like this after I have added Vanguard support.

**Comment by recursivecodes** [comment]
Any chance you'll be able to get to this soon?

**Comment by Lierrmm** [comment]
Added getLookupValues function in a661aa5 and live within https://www.npmjs.com/package/call-of-duty-api/v/2.2.1
