### ISSUE TITLE
Error from datastore from calling PSN / XBL Accounts

### ISSUE THREAD

**Issue by ChisdealHD** [Lierrmm/Node-CallOfDuty#8]
PSN and Xbox side API, COD have changed they mw API some reasons. because even i tried username from cod.tracker.gg example: ARWannabes as PSN name and returns that same error.

since i dont own COD MW i cant even test with my username see if is api fallback.

`{
  type: 'com.activision.mt.common.stdtools.exceptions.NoStackTraceException',
  message: 'Error from datastore'
}`

What this using is coming from COD API to Discord BOT

So all callout coming from Discord Server Self but only thing that runs is by command and as small preview.

`
if (args[1] === 'mw') {
                    var plat = args[2];

                    if (plat == "" || plat == null) return message.channel.sendMessage("Select platform `psn|xb1`");

                    if (plat = "psn") {

                        var username = message.content.split(" ").slice(4).join(" ");

                        if (username == "" || username == null) return message.channel.sendMessage("Enter your Username from that Platform");

                        var urlInput = defaultBaseURL + "crm/cod/v2/title/" + modernwarfare + "/platform/psn/gamer/" + username + "/profile/type/mp"
                        var options = {
                            method: 'get',
                            url: urlInput,
                            headers: {
                                "content-type": "application/json",
                                "User-Agent": userAgent,
                                'Cookie': "is here",
                            }
                        };

                        axios(options).then(body => {
                            console.log(body.data.data);
                            if (body.data.data.message !== "Not permitted: user not found") {
                                let embed = new Discord.RichEmbed();
                                embed.setColor(0x9900FF)
                                embed.setAuthor(dclient.user.username + "#" + dclient.user.discriminator, dclient.user.avatarURL, "")
                                embed.setTitle(message.author.username + "#" + message.author.discriminator + " COD API (Modern Warfare Multiplayer)")
                                embed.setDescription("Your Call of Duty Modern Warfare (Multiplayer)")
                                embed.setThumbnail("https://portforward.com/call-of-duty-modern-warfare/call-of-duty-modern-warfare-logo.png")
                                embed.addField("Level: ", body.data.data.level, inline = true)
                                embed.addField("Prestige: ", body.data.data.prestige, inline = true)
                                embed.addField("Melee Kills: ", body.data.data.lifetime.all.melee, inline = true)
                                embed.addField("Deaths: ", body.data.data.lifetime.all.deaths, inline = true)
                                embed.addField("Kills: ", body.data.data.lifetime.all.kills, inline = true)
                                embed.addField("Total Games Played: ", body.data.data.lifetime.all.gamesPlayed, inline = true)
                                embed.setTimestamp()
                                embed.setFooter("Sent via " + dclient.user.username + " Using COD-API", dclient.user.avatarURL)
                                message.channel.sendMessage({ embed })
                            } else {
                                let embed = new Discord.RichEmbed();
                                embed.setColor(0x9900FF)
                                embed.setAuthor(dclient.user.username + "#" + dclient.user.discriminator, dclient.user.avatarURL, "")
                                embed.setTitle(message.author.username + "#" + message.author.discriminator + " COD API (Modern Warfare Multiplayer)")
                                embed.setDescription("Your Call of Duty Modern Warfare (Multiplayer)")
                                embed.setThumbnail("https://portforward.com/call-of-duty-modern-warfare/call-of-duty-modern-warfare-logo.png")
                                embed.addField("Error: ", "404", inline = true)
                                embed.addField("Message: ", "User not Found? Check if Correct Username you just Entered", inline = true)
                                embed.setTimestamp()
                                embed.setFooter("Sent via " + dclient.user.username + " Using COD-API", dclient.user.avatarURL)
                                message.channel.sendMessage({ embed })
                            }
                        }).catch(err => console.log(err));

                    } else if (plat = "xb1") {

                        var username = message.content.split(" ").slice(4).join(" ");

                        if (username == "" || username == null) return message.channel.sendMessage("Enter your Username from that Platform");

                        var urlInput = defaultBaseURL + "crm/cod/v2/title/" + modernwarfare + "/platform/xb1/gamer/" + username + "/profile/type/mp"
                        var options = {
                            method: 'get',
                            url: urlInput,
                            headers: {
                                "content-type": "application/json",
                                "User-Agent": userAgent,
                                'Cookie': "is here",
                            }
                        };

                        axios(options).then(body => {
                            //console.log(body.data.data);
                            if (body.data.data.message !== "Not permitted: user not found") {
                                let embed = new Discord.RichEmbed();
                                embed.setColor(0x9900FF)
                                embed.setAuthor(dclient.user.username + "#" + dclient.user.discriminator, dclient.user.avatarURL, "")
                                embed.setTitle(message.author.username + "#" + message.author.discriminator + " COD API (Modern Warfare Multiplayer)")
                                embed.setDescription("Your Call of Duty Modern Warfare (Multiplayer)")
                                embed.setThumbnail("https://portforward.com/call-of-duty-modern-warfare/call-of-duty-modern-warfare-logo.png")
                                embed.addField("Level: ", body.data.data.level, inline = true)
                                embed.addField("Prestige: ", body.data.data.prestige, inline = true)
                                embed.addField("Melee Kills: ", body.data.data.lifetime.all.melee, inline = true)
                                embed.addField("Deaths: ", body.data.data.lifetime.all.deaths, inline = true)
                                embed.addField("Kills: ", body.data.data.lifetime.all.kills, inline = true)
                                embed.addField("Total Games Played: ", body.data.data.lifetime.all.gamesPlayed, inline = true)
                                embed.setTimestamp()
                                embed.setFooter("Sent via " + dclient.user.username + " Using COD-API", dclient.user.avatarURL)
                                message.channel.sendMessage({ embed })
                            } else {
                                let embed = new Discord.RichEmbed();
                                embed.setColor(0x9900FF)
                                embed.setAuthor(dclient.user.username + "#" + dclient.user.discriminator, dclient.user.avatarURL, "")
                                embed.setTitle(message.author.username + "#" + message.author.discriminator + " COD API (Modern Warfare Multiplayer)")
                                embed.setDescription("Your Call of Duty Modern Warfare (Multiplayer)")
                                embed.setThumbnail("https://portforward.com/call-of-duty-modern-warfare/call-of-duty-modern-warfare-logo.png")
                                embed.addField("Error: ", "404", inline = true)
                                embed.addField("Message: ", "User not Found? Check if Correct Username you just Entered", inline = true)
                                embed.setTimestamp()
                                embed.setFooter("Sent via " + dclient.user.username + " Using COD-API", dclient.user.avatarURL)
                                message.channel.sendMessage({ embed })
                            }
                        }).catch(err => console.log(err));

                    }
                    /*else if (plat = "pc") {

                                       var username = message.content.split(" ")[3].replace(/#/gmi, "%23");;
                                       username = username.replace(/([\w\W]*)%23\d+/gmi, '$1');
                                       console.log(username)

                                       if (username == "" || username == null) return message.channel.sendMessage("Enter your Username from that Platform");

                                       var urlInput = defaultBaseURL + "crm/cod/v2/title/" + modernwarfare + "/platform/battle/gamer/" + username + "/profile/type/mp"
                                       var options = {
                                           method: 'get',
                                           url: urlInput,
                                           headers: {
                                               "content-type": "application/json",
                                               "User-Agent": userAgent,
                                               'Cookie': "is here",
                                           }
                                       };

                                       axios(options).then(body => {
                                           //console.log(body.data.data);
                                           let embed = new Discord.RichEmbed();
                                           embed.setColor(0x9900FF)
                                           embed.setAuthor(dclient.user.username + "#" + dclient.user.discriminator, dclient.user.avatarURL, "")
                                           embed.setTitle(message.author.username + "#" + message.author.discriminator + " COD API (Modern Warfare Multiplayer)")
                                           embed.setDescription("Your Call of Duty Modern Warfare (Multiplayer)")
                                               //embed.setThumbnail(user.avatarURL)
                                           embed.addField("Level: ", body.data.data.level, inline = true)
                                           embed.addField("Prestige: ", body.data.data.prestige, inline = true)
                                           embed.addField("Melee Kills: ", body.data.data.lifetime.all.melee, inline = true)
                                           embed.addField("Deaths: ", body.data.data.lifetime.all.deaths, inline = true)
                                           embed.addField("Kills: ", body.data.data.lifetime.all.kills, inline = true)
                                           embed.addField("Total Games Played: ", body.data.data.lifetime.all.gamesPlayed, inline = true)
                                           embed.setTimestamp()
                                           embed.setFooter("Sent via " + dclient.user.username + " Using COD-API", dclient.user.avatarURL)
                                           message.channel.sendMessage({ embed })
                                       }).catch(err => console.log(err));

                                   }*/
                    else {
                        message.channel.sendMessage("You never Selected right Platform, Please Select `psn|xb1`")
                    }
                }

`

i only took bit of code from your LIB since your LIB wasn't even happy with discord LIB.

but everything works fine just cod MW some how has failed datastore background on error so im not sure they disabled API or not.

but i disable that command for now till i get response back.

**Comment by Lierrmm** [comment]
Check you cookies. If logged in to my.callofduty.com and you visit [This Endpoint](https://my.callofduty.com/api/papi-client/stats/cod/v1/title/mw/platform/psn/gamer/ARWannabes/profile/type/mp) , It will work, however, if you open an incognito tab and visit the same url, you will get the datastore issue.


Check that you set s_ACT_SSO_COOKIE as one of the cookies, this is the validation.

**Comment by ChisdealHD** [comment]
cookies what im using from your API preset

**Comment by ChisdealHD** [comment]
all rest works just fine just cod mw having issues

**Comment by Lierrmm** [comment]
Weird.

This is what I receive from the endpoint using the gamertag you produced.

![image](https://user-images.githubusercontent.com/13552261/70927228-8296fa00-2026-11ea-8795-a5a74d51bb36.png)

You also may get the datastore message when no data is defined.

**Comment by ChisdealHD** [comment]
thats odd, well returns me that message not info

**Comment by ChisdealHD** [comment]
nothing changed at all only changed is adding image using enbed for discord

**Comment by Lierrmm** [comment]
You should always handle that error, which is why in my wrapper, I throw an exception.

I will do some more testing regarding Discord and the API and see what I can find.

**Comment by ChisdealHD** [comment]
sure, i show you i getting but im not sure my end at all.
![Code_ArMnKT0QXP](https://user-images.githubusercontent.com/18028479/70927470-e91c1800-2026-11ea-9f71-5eb67c10c9f9.png)

**Comment by ChisdealHD** [comment]
i make error side for now but as see on console below thats response i get for cod mw

**Comment by Lierrmm** [comment]
I will do more investigation and hopefully can provide a fix/ feedback.

**Comment by ChisdealHD** [comment]
will do ty

**Comment by Lierrmm** [comment]
Just done some testing on MW and DISCORD:

```js
if(stripPrefix(msg.content) == "test") {
            api.MWmp("Lierrmm#2364", api.platforms.battle).then((data) => {
                msg.channel.send(`Recieved Data: ${data.username} - ${data.platform} - ${data.level}`);
                let embed = new Discord.RichEmbed();
                embed.setColor(0x9900FF);
                embed.setTitle(msg.author.username + "#" + msg.author.discriminator + " COD API (Modern Warfare Multiplayer)");
                embed.setDescription("Your Call of Duty Modern Warfare (Multiplayer)");
                embed.addField("Level: ", data.level, inline = true);
                embed.addField("Prestige: ", data.prestige, inline = true);
                embed.addField("Melee Kills: ", data.lifetime.all.properties.melee, inline = true);  //Doesn't exist
                embed.addField("Deaths: ", data.lifetime.all.properties.deaths, inline = true);
                embed.addField("Kills: ", data.lifetime.all.properties.kills, inline = true);
                embed.addField("Total Games Played: ", data.lifetime.all.properties.gamesPlayed, inline = true);
                embed.setTimestamp();
                msg.channel.sendMessage({ embed });
            }).catch((err) => {
                msg.channel.send(err);
            });
        }
```

returns correct data within discord. I also used your gamertag which also worked.

![image](https://user-images.githubusercontent.com/13552261/70930772-df49e300-202d-11ea-8169-a1abb45c55aa.png)


Just in case, I have pushed an update with edited cookies, so you may want to change those.

**Comment by ChisdealHD** [comment]
thats odd, why mine false?

**Comment by ChisdealHD** [comment]
will it be `const userAgent = "ChisdealHDAPP/1.0.1"` they blocked it? since i have custom userAgent

**Comment by ChisdealHD** [comment]
ah i found out issue, that errros me because tells me user hasn't played a game so doesn't detect it. when i do P-Hami as psn shows no stats so i thinking my side having issues or psn having issues
