### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by gcazin** [Lierrmm/Node-CallOfDuty#9]
Hello, any means to circumvent this problem?

**Comment by Flupster** [comment]
https://github.com/aishek/axios-rate-limit

This could be used to local rate limit if the developer adds it in, should be very simple to implement

**Comment by gcazin** [comment]
It's look good yes

Very useful to implement this!

**Comment by Lierrmm** [comment]
Will implement axios-rate-limit package later on and will add some defaults.

Will also allow these to be changed but up to the person using the API to handle the rate limit exceptions.

I will update this issue when completed.

Thanks! 😄

**Comment by Lierrmm** [comment]
Decided not to add the rate limit package as mentioned above but have added a login method which should reduce the rate-limiting unless you are hammering the API.

**Comment by Flupster** [comment]
> Decided not to add the rate limit package as mentioned above but have added a login method which should reduce the rate-limiting unless you are hammering the API.

I am still getting rate limited pretty heavily, I would recommend exposing the `apiAxios` in the module so we can add our own rate limits without modifying this package

It should be as simple as adding `module.axios = apiAxios;` into index,js

I would also like to request that if a request fails you don't hardcode "Rate Limited", instead let the catch block report the error

**Comment by Lierrmm** [comment]
Hi, @Flupster,

The API will only return rate-limited if you are in fact limited.

I will expose Axios in an update later today.

**Comment by Lierrmm** [comment]
Update:

I have added axios-rate-limit and exposed apiaxios too in this [commit](https://github.com/Lierrmm/Node-CallOfDuty/commit/3886b14ff54d3910c48a017aac74aa92a4375bf0)


Hope this helps.

**Comment by Flupster** [comment]
> Update:
> 
> I have added axios-rate-limit and exposed apiaxios too in this [commit](https://github.com/Lierrmm/Node-CallOfDuty/commit/3886b14ff54d3910c48a017aac74aa92a4375bf0)
> 
> Hope this helps.

Very nice, do you have any idea of the rate limit by cod?

Their headers don't supply any information, I was calling `MWcombatwz` and there was no rate limit for the use logged in, but if you were to check 3 or 4 different gamertags sporadically over a minute a rate limit got applied after a few minutes, so it leads me to believe their is a maximum requests per hour for the api, would be nice to have exact figures so the rate limit can be tuned perfectly to not get rate limited

**Comment by Lierrmm** [comment]
I haven't noticed any pattern with rate limits, I usually stick to a call every 4 seconds and it works fine. 
I would have to investigate further.
